### ISSUE TITLE
Cluster error

### ISSUE THREAD

**Issue by zhaishengfu** [mattnedrich/MeanShift_cpp#6]
thanks for sharing， but when i compile there is an error！
in the cpp_test.cpp, in line 49, your code is 
vector<vector<double> > shifted_points = msp->cluster(points, kernel_bandwidth);

but your cluster funtion returns vector<Cluster>, so i changed to the following:
vector<vector<double> > shifted_points = msp->cluster(points, kernel_bandwidth)[0] .support;
and i can change 0 to 1 also, the result is different, i think this is a big error

**Comment by zhaishengfu** [comment]
![00](https://cloud.githubusercontent.com/assets/7630101/21631022/9e28e612-d271-11e6-8f16-f7f034dd5005.png)

**Comment by mattnedrich** [comment]
made some changes, give it a shot now

**Comment by mattnedrich** [comment]
Going to close this, let me know if you still have an issue.
